# Development overrides for docker-compose
# This file is automatically loaded by docker-compose in development

version: '3.8'

services:
  app:
    # Development-specific settings
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
    environment:
      - PODCAST_KG_LOG_LEVEL=DEBUG
      - PYTHONDEBUG=1
    volumes:
      # Mount source code as read-write for development
      - ./src:/app/src
      - ./tests:/app/tests
      - ./scripts:/app/scripts
      # Mount config as read-write to test changes
      - ./config:/app/config
    # Keep container running for debugging
    command: ["tail", "-f", "/dev/null"]
    
  # Enable GPU support for Whisper if available
  # Uncomment the following lines if you have NVIDIA GPU
  # app:
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]