# Semantic Clustering Configuration
# 
# This file contains configuration parameters for the HDBSCAN clustering system.
# Adjust these parameters to tune clustering behavior.
#
# IMPORTANT: HDBSCAN is NOT self-healing. If results are poor, manually adjust
# these parameters and re-run clustering.

clustering:
  # Minimum cluster size calculation method
  # Options: 'sqrt' (dynamic based on data size) or 'fixed' (use fixed value)
  min_cluster_size_formula: 'sqrt'
  
  # If min_cluster_size_formula is 'fixed', use this value
  # Typical range: 5-50 depending on dataset size
  min_cluster_size_fixed: 10
  
  # Minimum number of samples in neighborhood for point to be core point
  # Lower values = more granular clusters
  # Typical range: 2-10
  min_samples: 3
  
  # Cluster selection epsilon for HDBSCAN
  # Controls how close points must be to merge into same cluster
  # Lower values = tighter, more numerous clusters
  # Higher values = looser, fewer clusters
  # Typical range: 0.1-0.5 for cosine distance on embeddings
  epsilon: 0.3

