# Component Dependencies Configuration
# 
# This file defines dependencies between components in the extraction pipeline.
# Components listed as dependencies must be enabled for the dependent component to function properly.

components:
  # Timestamp injection has no dependencies
  timestamp_injection:
    description: "Injects timestamps into extracted entities"
    depends_on: []
    optional_dependencies: []
    justification: |
      SimpleKGPipeline may not preserve temporal information from the source text.
      This component ensures timestamps are associated with entities when available.
    removal_criteria:
      - "SimpleKGPipeline natively preserves timestamps"
      - "Temporal information is not required for the use case"

  # Speaker injection depends on having speaker information
  speaker_injection:
    description: "Associates entities with speakers who mentioned them"
    depends_on: []
    optional_dependencies:
      - "diarization"  # Better results with speaker diarization
    justification: |
      SimpleKGPipeline may not track which speaker mentioned which entity.
      This component maintains speaker-entity relationships for attribution.
    removal_criteria:
      - "SimpleKGPipeline tracks speaker attribution natively"
      - "Speaker information is not relevant to the use case"

  # Quote post-processing enhances quote extraction
  quote_postprocessing:
    description: "Enhances quotes with speaker and context information"
    depends_on: []
    optional_dependencies:
      - "speaker_injection"  # Better quote attribution with speakers
      - "timestamp_injection"  # Temporal context for quotes
    justification: |
      SimpleKGPipeline may extract quotes without full context.
      This component enriches quotes with speaker, timing, and surrounding context.
    removal_criteria:
      - "SimpleKGPipeline provides comprehensive quote extraction"
      - "Basic quote extraction is sufficient"

  # Metadata enrichment adds contextual information
  metadata_enrichment:
    description: "Enriches entities with podcast and episode metadata"
    depends_on: []
    optional_dependencies: []
    justification: |
      SimpleKGPipeline may not associate entities with their source context.
      This component adds podcast, episode, and segment metadata to entities.
    removal_criteria:
      - "SimpleKGPipeline includes source metadata automatically"
      - "Source tracking is not required"

  # Entity resolution post-processing improves entity matching
  entity_resolution_postprocess:
    description: "Resolves and merges duplicate entities after extraction"
    depends_on: []
    optional_dependencies:
      - "metadata_enrichment"  # Better resolution with metadata
    justification: |
      SimpleKGPipeline may create duplicate entities for the same real-world entity.
      This component identifies and merges duplicates based on similarity.
    removal_criteria:
      - "SimpleKGPipeline has robust entity resolution built-in"
      - "Duplicate entities are acceptable for the use case"
      - "Entity resolution V2 feature flag provides better results"

# Validation rules
validation:
  # If a component is disabled, its dependents should be warned
  warn_on_missing_dependency: true
  
  # If a component is disabled but has dependents, prevent startup
  fail_on_broken_dependency: false
  
  # Components that can be safely disabled without warnings
  safe_to_disable:
    - "quote_postprocessing"
    - "metadata_enrichment"

# Performance impact expectations
performance_impact:
  timestamp_injection:
    expected_overhead_ms: 50
    memory_overhead_mb: 10
    
  speaker_injection:
    expected_overhead_ms: 100
    memory_overhead_mb: 20
    
  quote_postprocessing:
    expected_overhead_ms: 200
    memory_overhead_mb: 50
    
  metadata_enrichment:
    expected_overhead_ms: 30
    memory_overhead_mb: 5
    
  entity_resolution_postprocess:
    expected_overhead_ms: 500
    memory_overhead_mb: 100