# Entity Resolution Rules Configuration
# This file defines rules for resolving entity aliases and variations

# Similarity thresholds for different match types
thresholds:
  exact_match: 1.0
  case_insensitive: 0.95
  alias_match: 0.9
  abbreviation_match: 0.9
  singular_plural: 0.9
  fuzzy_match: 0.85
  
# Configuration options
options:
  case_sensitive: false
  use_aliases: true
  use_abbreviations: true
  merge_singular_plural: true
  max_merge_distance: 3
  confidence_weight: true

# Domain-specific alias groups
# Each group contains variations that refer to the same entity
aliases:
  # Technology terms
  - ["AI", "Artificial Intelligence", "A.I.", "artificial intelligence", "Artificial intelligence"]
  - ["ML", "Machine Learning", "machine learning", "Machine learning"]
  - ["DL", "Deep Learning", "deep learning", "Deep learning"]
  - ["NLP", "Natural Language Processing", "natural language processing"]
  - ["CV", "Computer Vision", "computer vision"]
  - ["LLM", "Large Language Model", "Large Language Models", "large language model", "large language models"]
  - ["GPT", "Generative Pre-trained Transformer", "generative pre-trained transformer"]
  - ["API", "Application Programming Interface", "application programming interface"]
  - ["SDK", "Software Development Kit", "software development kit"]
  - ["IDE", "Integrated Development Environment", "integrated development environment"]
  
  # Company names and variations
  - ["Google", "Google LLC", "Google Inc.", "Google Inc", "Alphabet"]
  - ["Microsoft", "Microsoft Corporation", "Microsoft Corp.", "Microsoft Corp", "MSFT"]
  - ["Apple", "Apple Inc.", "Apple Inc", "Apple Computer", "AAPL"]
  - ["Amazon", "Amazon.com", "Amazon Web Services", "AWS", "AMZN"]
  - ["Facebook", "Meta", "Meta Platforms", "FB"]
  - ["OpenAI", "Open AI", "open ai"]
  
  # Academic institutions
  - ["MIT", "Massachusetts Institute of Technology", "M.I.T."]
  - ["Stanford", "Stanford University", "Stanford U"]
  - ["Harvard", "Harvard University", "Harvard U"]
  - ["CMU", "Carnegie Mellon", "Carnegie Mellon University"]
  - ["Berkeley", "UC Berkeley", "University of California Berkeley", "UCB"]
  
  # Medical/Health terms
  - ["COVID", "COVID-19", "Covid-19", "Coronavirus", "SARS-CoV-2"]
  - ["WHO", "World Health Organization", "W.H.O."]
  - ["CDC", "Centers for Disease Control", "Centers for Disease Control and Prevention"]
  - ["FDA", "Food and Drug Administration", "F.D.A."]
  
  # Business terms
  - ["CEO", "Chief Executive Officer", "chief executive officer"]
  - ["CTO", "Chief Technology Officer", "chief technology officer"]
  - ["CFO", "Chief Financial Officer", "chief financial officer"]
  - ["ROI", "Return on Investment", "return on investment"]
  - ["KPI", "Key Performance Indicator", "key performance indicator", "KPIs"]
  - ["B2B", "Business to Business", "business-to-business"]
  - ["B2C", "Business to Consumer", "business-to-consumer"]
  - ["SaaS", "Software as a Service", "software as a service"]
  
  # Geographic locations
  - ["US", "USA", "United States", "United States of America", "U.S.", "U.S.A."]
  - ["UK", "United Kingdom", "Britain", "Great Britain", "U.K."]
  - ["EU", "European Union", "E.U."]
  - ["NYC", "New York City", "New York", "NY"]
  - ["LA", "Los Angeles", "L.A."]
  - ["SF", "San Francisco", "San Fran"]

# Abbreviation expansions
abbreviations:
  # Titles
  "Dr.": "Doctor"
  "Mr.": "Mister"
  "Mrs.": "Missus"
  "Ms.": "Miss"
  "Prof.": "Professor"
  "Sr.": "Senior"
  "Jr.": "Junior"
  
  # Academic degrees
  "PhD": "Doctor of Philosophy"
  "MD": "Medical Doctor"
  "JD": "Juris Doctor"
  "MBA": "Master of Business Administration"
  "BS": "Bachelor of Science"
  "BA": "Bachelor of Arts"
  "MS": "Master of Science"
  "MA": "Master of Arts"
  
  # Time periods
  "Jan": "January"
  "Feb": "February"
  "Mar": "March"
  "Apr": "April"
  "Jun": "June"
  "Jul": "July"
  "Aug": "August"
  "Sep": "September"
  "Sept": "September"
  "Oct": "October"
  "Nov": "November"
  "Dec": "December"
  
  # Common abbreviations
  "vs.": "versus"
  "vs": "versus"
  "etc.": "et cetera"
  "etc": "et cetera"
  "i.e.": "that is"
  "e.g.": "for example"
  "Corp.": "Corporation"
  "Inc.": "Incorporated"
  "Ltd.": "Limited"
  "Co.": "Company"

# Irregular plural forms
irregular_plurals:
  "person": "people"
  "child": "children"
  "man": "men"
  "woman": "women"
  "tooth": "teeth"
  "foot": "feet"
  "mouse": "mice"
  "goose": "geese"
  "datum": "data"
  "index": "indices"
  "matrix": "matrices"
  "vertex": "vertices"
  "analysis": "analyses"
  "crisis": "crises"
  "phenomenon": "phenomena"
  "criterion": "criteria"

# Domain-specific rules
domain_rules:
  # Technology domain
  technology:
    # Merge version numbers
    merge_versions: true  # "Python 3.8" and "Python 3.9" -> "Python"
    # Common suffixes to ignore
    ignore_suffixes: ["framework", "library", "platform", "system", "tool"]
    
  # Medical domain
  medical:
    # Merge drug brand/generic names
    merge_drug_names: true
    # Common medical suffixes
    medical_suffixes: ["syndrome", "disease", "disorder", "condition"]
    
  # Business domain
  business:
    # Merge company legal suffixes
    merge_legal_forms: true  # "Apple Inc." and "Apple" -> "Apple"
    legal_suffixes: ["Inc.", "Inc", "LLC", "Ltd.", "Ltd", "Corp.", "Corp", "Co.", "Co"]

# Exclusion rules - entities that should never be merged
exclusions:
  # Don't merge these even if similar
  - ["Java", "JavaScript"]  # Different programming languages
  - ["React", "React Native"]  # Different frameworks
  - ["Machine Learning", "Deep Learning"]  # Related but distinct concepts
  - ["Virus", "Bacteria"]  # Different types of pathogens
  - ["Depression", "Recession"]  # Different contexts (medical vs economic)