version: '1.0'
podcasts:
- id: mel_robbins_podcast
  name: The Mel Robbins Podcast
  rss_feed_url: https://feeds.simplecast.com/UCwaTX1J
  enabled: true
  database:
    uri: neo4j://localhost:7687
    neo4j_port: 7687
    neo4j_password: password
    database_name: neo4j
  processing:
    batch_size: 10
    max_retries: 3
    enable_flow_analysis: true
    enable_graph_enhancement: true
    use_large_context: true
  metadata:
    description: Motivational content and life advice from Mel Robbins
    language: en
    category: Self-Improvement
    tags:
    - motivation
    - self-help
    - personal-development
    host: Mel Robbins
    website: https://melrobbins.com
  persona:
    podcast_name: The Mel Robbins Podcast
    host_style_summary: Mel Robbins' hosting style is energetic, relatable, and 
      deeply personal.  She interweaves  expert interviews with anecdotes from 
      her own life, creating a conversational and engaging tone.  Her 
      interactions with guests are warm and collaborative, fostering open and 
      insightful discussions.
    core_themes:
    - Mindset
    - Mental Toughness
    - Resilience
    - Anxiety
    - Hormones
    - Women's Health
    - Self-Improvement
    - Personal Growth
    - Relationships
    target_audience: The target audience is primarily women interested in 
      self-improvement, personal growth, and mental and physical well-being. The
      podcast also appeals to individuals who seek practical advice and 
      relatable stories to navigate life challenges and build resilience.  It's 
      not limited to a specific age group, as its topics are relevant across 
      life stages.
    prompt_directive: You are Mel Robbins, a motivational speaker and podcast 
      host.  You're energetic, friendly, and deeply invested in your listeners' 
      well-being.  You speak directly to the listener, using relatable anecdotes
      and stories from your life to illustrate key concepts. You seamlessly 
      blend personal experiences with expert advice, often employing a 
      conversational, almost chatty tone. When speaking with guests, you're 
      warm, collaborative, and focused on extracting actionable advice that 
      listeners can apply to their own lives. You often use colorful language, 
      metaphors, and personal experiences, and your enthusiasm is infectious.
- id: my_first_million
  name: My First Million
  rss_feed_url: https://feeds.megaphone.fm/HS2300184645
  enabled: true
  database:
    uri: neo4j://localhost:7688
    neo4j_port: 7688
    neo4j_password: password
    database_name: neo4j
  processing:
    batch_size: 10
    max_retries: 3
    enable_flow_analysis: true
    enable_graph_enhancement: true
    use_large_context: true
  metadata:
    description: Business and entrepreneurship insights from successful founders
    language: en
    category: Business
    tags:
    - entrepreneurship
    - business
    - investing
    - technology
    host: Sam Parr and Shaan Puri
    website: https://thehustle.co/my-first-million-podcast
  persona:
    podcast_name: My First Million
    host_style_summary: The hosts of My First Million adopt a conversational, 
      informal, and often humorous tone.  They interject frequently, sharing 
      personal anecdotes and experiences related to the guest's topics, creating
      a dynamic and engaging discussion.
    core_themes:
    - Investing (particularly high-risk, high-reward strategies)
    - Entrepreneurship
    - Personal Finance
    - Business Ideas
    - Technology Trends (especially AI)
    target_audience: Ambitious, entrepreneurial-minded individuals, particularly
      men in their 20s and 30s, interested in wealth creation, business 
      strategies, and personal development.  Listeners are generally comfortable
      with complex financial and technological concepts and appreciate a candid,
      humorous approach.
    prompt_directive: You are a co-host on the My First Million podcast.  Speak 
      conversationally,  freely interjecting with relevant personal anecdotes 
      and humorous commentary. Don't be afraid to be opinionated and share your 
      unique perspective, even if it's controversial.  Focus on practical advice
      and insights, but keep the tone lighthearted and engaging.  Don't be 
      afraid to challenge the guest or your co-host, and embrace a dynamic, 
      fast-paced discussion.
defaults:
  batch_size: 10
  max_retries: 3
  enable_flow_analysis: true
  enable_graph_enhancement: true
  use_large_context: true
