# VTT Knowledge Pipeline Configuration
# This file contains all non-secret configuration settings
# Copy to config.yml and customize as needed

# VTT Processing Settings
vtt_processing:
  input_directories:
    - "./transcripts"
  file_pattern: "*.vtt"
  recursive: true
  merge_short_segments: true
  min_segment_duration: 2.0
  use_directory_name_as_podcast: true
  metadata_file_name: "metadata.json"
  infer_episode_title_from_filename: true

# Processing Settings
min_segment_tokens: 150
max_segment_tokens: 800

# Embedding Settings
embedding_dimensions: 1536
embedding_similarity: "cosine"
embedding_model: "text-embedding-ada-002"
embedding_provider: "sentence_transformer"  # or "openai"

# File Paths (relative to working directory)
base_dir: "."
output_dir: "processed_transcripts"
checkpoint_dir: "checkpoints"

# Knowledge Extraction Settings
use_large_context: true
enable_graph_enhancements: true
use_schemaless_extraction: false  # Set to true for schemaless mode

# Schemaless Settings (if enabled)
schemaless_confidence_threshold: 0.7
entity_resolution_threshold: 0.85
max_properties_per_node: 50
relationship_normalization: true

# Progress and Monitoring
checkpoint_interval: 10  # Save after N files
memory_cleanup_interval: 5  # Cleanup after N files

# Batch Processing
batch_size: 10
embedding_batch_size: 50
save_checkpoints: true
checkpoint_every_n: 5

# Progress Settings
enable_progress_bar: true
show_memory_usage: true

# Interactive Features
interactive_mode: false
save_visualizations: false
generate_reports: false
verbose_logging: false

# Rate Limiting
llm_requests_per_minute: 60
llm_tokens_per_minute: 150000
embedding_requests_per_minute: 500

# Retry Settings
max_retries: 3
retry_delay: 1.0
exponential_backoff: true

# Resource Limits
max_concurrent_llm_jobs: 4
max_memory_gb: 4.0

# Model Selection
llm_provider: "gemini"  # or "openai", "anthropic"
models:
  primary_llm: "gemini-2.0-flash"
  fallback_llm: "gemini-1.5-flash"

# Task Routing
task_routing:
  insights:
    - "gemini-2.0-flash"
    - "gemini-1.5-flash"
  entities:
    - "gemini-2.0-flash"
    - "gemini-1.5-flash"
  quotes:
    - "gemini-2.0-flash"
    - "gemini-1.5-flash"
  complexity:
    - "gemini-1.5-flash"
  density:
    - "gemini-1.5-flash"

# Advanced Settings
enable_experimental_features: false
enable_debug_mode: false
enable_profiling: false

# Cache Settings
cache_ttl: 900  # seconds
max_cache_size: 1000  # entries

# Health Check Settings
health_check_interval: 60  # seconds
provider_timeout: 30  # seconds

# Entity Resolution Rules
entity_resolution:
  enabled: true
  min_similarity: 0.85
  max_distance: 0.15

# Graph Provider Settings
graph_provider: "neo4j"  # or "schemaless", "compatible"
neo4j:
  connection_timeout: 30
  max_connection_lifetime: 3600
  max_connection_pool_size: 50
  connection_acquisition_timeout: 60