# Default Configuration for Podcast Transcription Pipeline
# All settings can be overridden by environment variables

# API Configuration
api:
  # Timeout for API requests in seconds
  timeout: 300
  
  # Retry configuration (max 2 retries to preserve daily quota)
  retry:
    max_attempts: 2
    backoff_multiplier: 2
    max_backoff: 30
  
  # Daily quota settings
  quota:
    max_episodes_per_day: 12
    max_requests_per_key: 25
    max_tokens_per_key: 1000000

# Processing Configuration
processing:
  # Sequential processing only (due to rate limits)
  parallel_workers: 1
  
  # Progress tracking
  enable_progress_bar: true
  checkpoint_enabled: true
  
  # Episode length limits (in minutes)
  max_episode_length: 60

# Output Configuration
output:
  # Default output directory
  default_dir: "data/transcripts"
  
  # File naming patterns
  naming:
    pattern: "{podcast_name}/{date}_{episode_title}.vtt"
    sanitize_filenames: true
    max_filename_length: 200
  
  # VTT format settings
  vtt:
    include_metadata: true
    speaker_voice_tags: true
    timestamp_precision: 3  # milliseconds

# Logging Configuration
logging:
  # Log levels: DEBUG, INFO, WARNING, ERROR, CRITICAL
  console_level: "INFO"
  file_level: "DEBUG"
  
  # Log file settings
  max_file_size_mb: 10
  backup_count: 5
  
  # Log directories
  log_dir: "logs"

# Security Configuration
security:
  # Environment variable names for API keys
  api_key_vars:
    - "GEMINI_API_KEY_1"
    - "GEMINI_API_KEY_2"
  
  # Key rotation settings
  rotation:
    strategy: "round_robin"  # round_robin or random
    fail_over_enabled: true

# Development Configuration
development:
  # Enable dry run mode by default
  dry_run: false
  
  # Debug settings
  debug_mode: false
  save_raw_responses: false
  
  # Test mode settings
  test_mode: false
  mock_api_calls: false