# This is a template. Create actual secrets using kubectl or a secrets management tool.
# DO NOT commit actual secrets to version control!
#
# To create this secret:
# kubectl create secret generic podcast-kg-secrets \
#   --from-literal=NEO4J_PASSWORD=your-password \
#   --from-literal=GOOGLE_API_KEY=your-api-key \
#   --from-literal=REDIS_PASSWORD=your-redis-password \
#   -n podcast-kg
#
# Or use this template with base64 encoded values:

apiVersion: v1
kind: Secret
metadata:
  name: podcast-kg-secrets
  namespace: podcast-kg
  labels:
    app.kubernetes.io/name: podcast-kg-pipeline
    app.kubernetes.io/component: secrets
type: Opaque
data:
  # Base64 encoded values (example only - replace with real values)
  # echo -n 'your-password' | base64
  NEO4J_PASSWORD: eW91ci1wYXNzd29yZA==  # REPLACE ME
  GOOGLE_API_KEY: eW91ci1hcGkta2V5     # REPLACE ME
  REDIS_PASSWORD: eW91ci1yZWRpcy1wYXNzd29yZA==  # REPLACE ME