apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: podcast-kg-data
  namespace: podcast-kg
  labels:
    app.kubernetes.io/name: podcast-kg-pipeline
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: fast-ssd  # Adjust based on your cluster

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: podcast-kg-logs
  namespace: podcast-kg
  labels:
    app.kubernetes.io/name: podcast-kg-pipeline
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: podcast-kg-cache
  namespace: podcast-kg
  labels:
    app.kubernetes.io/name: podcast-kg-pipeline
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: fast-ssd  # Use fast storage for cache