apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: podcast-kg

resources:
  - 01-namespace.yaml
  - 02-configmap.yaml
  - 03-secret.yaml
  - 04-pvc.yaml
  - 05-neo4j.yaml
  - 06-redis.yaml
  - 07-deployment.yaml
  - 08-job.yaml
  - 09-hpa.yaml
  - 10-networkpolicy.yaml
  - 11-ingress.yaml

images:
  - name: your-registry/podcast-kg-pipeline
    newTag: latest

configMapGenerator:
  - name: podcast-kg-config
    behavior: merge
    files:
      - config.yml
      - logging.conf

secretGenerator:
  - name: podcast-kg-secrets
    behavior: replace
    envs:
      - secrets.env

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: podcast-kg-pipeline
      namespace: podcast-kg
    spec:
      template:
        spec:
          containers:
          - name: podcast-kg
            env:
            - name: ENVIRONMENT
              value: production

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/version: v1.0.0

replicas:
  - name: podcast-kg-pipeline
    count: 3
  - name: redis
    count: 1
  - name: neo4j
    count: 1