version: '3.8'

# Docker Compose configuration for Neo4j databases
# Created as part of the Neo4j upgrade for neo4j-graphrag compatibility
# Date: June 28, 2025

services:
  # Mel Robbins Podcast Neo4j Database
  neo4j-mel-robbins:
    image: neo4j:5.25.1
    container_name: neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      # Bind mounts for data persistence
      - /home/sergeblumenfeld/neo4j/data:/data
      - /home/sergeblumenfeld/neo4j/logs:/logs
      - /home/sergeblumenfeld/neo4j/plugins:/plugins
      - /home/sergeblumenfeld/neo4j/import:/var/lib/neo4j/import
    networks:
      - podcast-network
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "password", "RETURN 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # My First Million Neo4j Database
  neo4j-my-first-million:
    image: neo4j:latest  # Using preview version 2025.05.1 - cannot downgrade due to log format
    container_name: neo4j-my_first_million
    restart: unless-stopped
    ports:
      - "7488:7474"  # HTTP
      - "7688:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    volumes:
      # Using Docker volumes (external)
      - neo4j_my_first_million_data:/data
      - neo4j_my_first_million_logs:/logs
    networks:
      - podcast-network
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "password", "RETURN 1"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  podcast-network:
    driver: bridge

volumes:
  # External volumes for my_first_million database
  # These volumes must exist before running docker-compose
  neo4j_my_first_million_data:
    external: true
    name: b15821420d80e9036923568a63989e465f86d6c90ed310eb597cf33b2b5afae8
  neo4j_my_first_million_logs:
    external: true
    name: 55450dc0541af7fa8aaa3779741bd8924783711d42f816f0986489cbb262745c

# Usage Instructions:
# 1. To start both databases: docker-compose -f docker-compose.neo4j.yml up -d
# 2. To stop both databases: docker-compose -f docker-compose.neo4j.yml down
# 3. To view logs: docker-compose -f docker-compose.neo4j.yml logs -f
# 4. To restart a specific service: docker-compose -f docker-compose.neo4j.yml restart neo4j-mel-robbins

# Important Notes:
# - mel_robbins_podcast uses Neo4j 5.25.1 (upgraded from 5.15.0)
# - my_first_million uses neo4j:latest (preview 2025.05.1) - cannot be downgraded
# - All data is persisted in volumes/bind mounts
# - Default credentials: neo4j/password